name: Feature Branch Workflow

on:
  push:
    branches: [feat/*]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"

      - name: ğŸ“¦ Setting up pnpm
        run: npm install -g pnpm && pnpm install

      - name: ğŸ“ Lint and format
        run: pnpm lint && pnpm format:check

      - name: ğŸ§ª Run unit tests and check coverage
        run: pnpm test:unit:coverage
